### ISSUE TITLE
Activate not working?

### ISSUE THREAD

**Issue by andrew-kennedy** [fisherman/pyenv#4]
I have pyenv installed and this plugin as well, and I can't seem to activate virtualenvs. Does this fisher plugin support activating virtualenvs?

**Comment by daenney** [comment]
No. This is pyenv, a Python versions manager: https://github.com/yyuu/pyenv. There's a pyenv plugin to help you manage virtual envs but that's not what pyenv does by itself.

**Comment by andrew-kennedy** [comment]
Cool, may have to look into writing a plugin. I like having fisherman handle pyenv instead of adding that line to my config.fish.

**Comment by daenney** [comment]
Yeah. The main reason we created a plugin is because that initialisation thing does a number of stupid things, including generate a full completion every time you start a new shell. By putting that into a separate function in `completions.d` the completions are only generated once per session if and only if you trigger the completion mechanism for the pyenv command.

**Comment by sooheon** [comment]
So what is the actual fix for this? I've tried adding 
`status --is-interactive; and . (pyenv virtualenv-init -|psub)` to my config.fish, no cigar.

**Comment by bucaran** [comment]
Sorry to ask. What's the desired behavior?

**Comment by sooheon** [comment]
pyenv and pyenv virtualenv ask you to put something like this in the config: `status --is-interactive; and . (pyenv init -|psub); and . (pyenv virtualenv-init -|psub)`. This works, but this fisherman pyenv plugin tells me that this is inefficient, causing startup slowdown, and does the pyenv initialization in a more 'fishy' way. The desired behavior is to also have this 'fishy' way of initializing pyenv-virtualenv.
