### ISSUE TITLE
pyenv not found

### ISSUE THREAD

**Issue by pmatos** [fisherman/pyenv#8]
After installing the plugin I try to do a `pyenv activate...` but I am told it cannot be found.

```
fish: pyenv: command not found...
~/.config/fish/functions/pyenv.fish (line 9): 
            command pyenv "$command" $argv
                    ^
in function “pyenv”
        called on standard input
        with parameter list “activate py-devtools-venv”
```

However, I have `pyenv` in the normal path `$HOME/.pyenv`.

**Comment by pmatos** [comment]
I noticed that `PATH` is not updated in `pyenv.fish`. Why is this? Usually `PATH` to pyenv is defined in terms of `PYENV_ROOT`, which is defined in `pyenv.fish`. Why not do `set -x PATH $PYENV_ROOT/bin $PATH` there?

**Comment by pmatos** [comment]
A call to `pyenv init` also seems to be missing.

**Comment by pmatos** [comment]
OK, I added `set -x PATH $HOME/.pyenv/bin $PATH` to `~/.config/fish/conf.d/000-env.fish`.

But I still get:
```
Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```

This is most likely because `pyenv init` was not called.

**Comment by pmatos** [comment]
If I do `pyenv init` myself in `config.fish` it works, but why isn't this done by the plugin?

**Comment by daenney** [comment]
It doesn't call `pyenv init` b/c this plugin replaces that functionality. Hence this line in the README: 

> This plugin replaces what status --is-interactive; and . (pyenv init -|psub) does in a more fishy way. This brings the startup time of your shell down as we do not generate full completions every time the shell starts but only when pyenv gets called.

The pyenv plugin, this one, doesn't know about, or take care of, pyenv-virtualenv, hence why you get that error message. These two things are not the same. However, in order to initialise pyenv-virtualenv you can simply call `status --is-interactive; and source (pyenv virtualenv-init -|psub)` as noted in the https://github.com/pyenv/pyenv-virtualenv README. However, when you call `pyenv init` it will nowadays also initialise any plugins, which is the behaviour you're seeing.

Remove the call to `pyenv init` from `config.fish` and replace it with the `pyenv virtualenv-init` call instead and everything will still work.

**Comment by pmatos** [comment]
@daenney makes sense. Now working. Thanks.
